### ISSUE TITLE
Problems that I meeted in paper's replication

### ISSUE THREAD

**Issue by Christophe-Jia** [PaulAlbert31/SNCF#1]
Hi,
I was in replicating this work with non-comercial propose, but I'm confused and stuck.
When I was trying to visualize the separation between clean and ood samples, it seems that the well-trained weights that you provided have some problems ? (but I'm not certain of that)
All weights with 'places' in its name are good, but the others without 'places' which indicates weights of imagenet exp meet a mismatch in model keys.
![截屏2022-09-20 15 49 04](https://user-images.githubusercontent.com/54699060/191199032-b5d3c6de-2242-4ceb-a13c-7c5ee3ad566a.png)
Thanks in advance and looking forward for your help!

**Comment by PaulAlbert31** [comment]
Hi, 
Thanks for pointing this out. There seem to have been a mix-up in the ImageNet OOD weight files, the one I uploaded were trained using a different projection head.
I'll update the weight repository as training progresses, the ones for 20% ImageNet OOD noise are now updated.

**Comment by Christophe-Jia** [comment]
Awosome! Thanks for your help and excellent work.
